# Change these first
owner: then77 # Your GitHub organization or username, where this repository lives
repo: web-uptime # The name of this repository

sites:
  - name: Main Website
    url: https://realzzy.xyz
    __dangerous__body_down: "Maintenance"
  - name: v2 Website
    url: https://v2.realzzy.xyz
  - name: Old Website
    url: https://v1.realzzy.xyz

status-website:
  cname: uptime.realzzy.xyz
  logoUrl: https://v1.realzzy.xyz/icon.png
  favicon: https://v1.realzzy.xyz/icon.png
  name: Realzzy Status
  introTitle: "**Realzzy Uptime Status** for monitoring."
  introMessage: "You can see all my websites, api, etc. (idk) if they're online or not."
  theme: night
  css: 'nav{animation:1s ease-in-out fadeInDown}main{animation:1s ease-in-out fadeIn}'
  links:
    - rel: stylesheet
      href: https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://realzzy.xyz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: "Current Downtime"
  footer: "(c) 2023 By [**Realzzy**](https://realzzy.xyz). Powered by [**Upptime**](https://upptime.js.org)"
