# Change these first
owner: then77 # Your GitHub organization or username, where this repository lives
repo: web-uptime # The name of this repository

sites:
  - name: Main Website
    url: https://therealzzy.xyz
    __dangerous__body_down: "Repl Unavailable"
  - name: API Website
    url: https://api.therealzzy.xyz
    __dangerous__body_down: "Repl Unavailable"
  - name: Old Website
    url: https://site.therealzzy.xyz
    __dangerous__body_down: "Repl Unavailable"
  - name: Files CDN
    url: https://files.therealzzy.xyz
    __dangerous__body_down: "Repl Unavailable"
  - name: My Shortlink Website
    url: $REALZZY_SHORTLINK
    __dangerous__body_down: "Repl Unavailable"
  - name: Jupyter Lab
    url: https://pylab.therealzzy.xyz
  - name: MC Test Server
    check: "tcp-ping"
    url: https://play.therealzzy.xyz
    port: 25565

status-website:
  cname: uptime.therealzzy.xyz
  logoUrl: https://therealzzy.xyz/icon.png
  favicon: https://therealzzy.xyz/icon.png
  name: Realzzy Status
  introTitle: "**Realzzy Uptime Status** for monitoring."
  introMessage: "You can see all my websites, api, etc. (idk) if they're online or not."
  theme: night
  js: 'window.onload=()=>{document.querySelector("nav").classList.add("animate__animated","animate__fadeInDown"),document.querySelector("main").classList.add("animate__animated","animate__fadeInUp")};'
  links:
    - rel: stylesheet
      href: https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://therealzzy.xyz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: "Current Downtime"
  footer: "(c) 2023 By [**Realzzy**](https://therealzzy.xyz). Powered by [**Upptime**](https://upptime.js.org)"
